services:
    dotnet:
        hostname: ${PROJECT}-dotnet
        extends:
            file: ../common/docker-compose.yaml
            service: base
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
            - secrets:/home/${CONTAINER_USER}/.microsoft/usersecrets
            - msal:/home/${CONTAINER_USER}/.local/.IdentityService
        build:
            context: .
            additional_contexts:
                localhost/base: service:base

volumes:
    root:
    secrets:
    msal:
