services:
    code:
        extends:
            file: ../common/docker-compose.yaml
            service: base
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
            - vscode:/home/${CONTAINER_USER}/.vscode
            - vscode-server:/home/${CONTAINER_USER}/.vscode-server
            - cache:/home/${CONTAINER_USER}/.cache
        build:
            context: .
            additional_contexts:
                localhost/base: service:base
        ports:
            - 8080:8080
volumes:
    root:
    vscode:
    vscode-server:
    cache:
