include:
  - services/common/docker-compose.yaml
  - services/code/docker-compose.yaml
  - services/node/docker-compose.yaml
  - services/cli/docker-compose.yaml
  - services/dotnet/docker-compose.yaml
  - services/git/docker-compose.yaml
  - services/gui/docker-compose.yaml
  - services/python/docker-compose.yaml
  - services/jupyter/docker-compose.yaml
