#!/usr/bin/env python3
"""
pot.py — Runs a one-off command against the 'default' DockerSeed service.

Usage:
    ./pot.py <command> [args...]

Reuses the 'default' service already built by harvest.py / docker-compose
build (see containers.json: a plain, template-less service) — it never
builds anything itself. Its generated services/default/docker-compose.yaml
already carries the standard security hardening (cap_drop, read_only,
tmpfs, no-new-privileges) that sow.py applies to every generated service,
so pot.py only needs to override the volume mount and working directory:
the current working directory is bind-mounted read-only at $HOME/$PROJECT,
replacing the named 'root' volume for this one-off run.

Uses the root docker-compose.yaml generated by harvest.py (rather than
combining common/ and services/default/ compose files by hand), so that
relative build-context paths and ${COMPOSE_PROJECT_NAME} interpolation
resolve exactly as they do for harvest.py's own `docker-compose build`.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR: Path = Path(__file__).resolve().parent
WORK_DIR: Path = Path.cwd()
ENV_FILE: Path = WORK_DIR / ".env"
COMPOSE_FILE: Path = SCRIPT_DIR / "docker-compose.yaml"
SERVICE_NAME: str = "default"

# Fallbacks used if a variable is missing from .env.
DEFAULT_ENV: dict[str, str] = {
    "CONTAINER_USER": "user",
    "CONTAINER_USER_ID": "1337",
    "PROJECT": "project",
}


def load_env(env_file: Path) -> dict[str, str]:
    env: dict[str, str] = dict(DEFAULT_ENV)
    if not env_file.exists():
        return env

    with open(env_file) as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or "=" not in stripped:
                continue
            name, _, value = stripped.partition("=")
            if value:
                env[name] = value
    return env


def main() -> None:
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <command> [args...]", file=sys.stderr)
        sys.exit(1)

    command = sys.argv[1:]
    mount_dir = Path.cwd()

    if shutil.which("docker") is None:
        print("Error: `docker` is not installed or not in PATH.", file=sys.stderr)
        sys.exit(1)

    if not COMPOSE_FILE.exists():
        print(
            f"Error: {COMPOSE_FILE} not found — run ./harvest.py first to "
            "generate the root docker-compose.yaml.",
            file=sys.stderr,
        )
        sys.exit(1)

    env = load_env(ENV_FILE)
    target = f"/home/{env['CONTAINER_USER']}/{env['PROJECT']}"

    result = subprocess.run(
        [
            "docker",
            "compose",
            "-f",
            str(COMPOSE_FILE),
            "run",
            "--rm",
            "-v",
            f"{mount_dir}:{target}:ro",
            "-w",
            target,
            SERVICE_NAME,
            *command,
        ],
        env={**os.environ, **env},
        cwd=SCRIPT_DIR,
    )

    if result.returncode == 125:
        print(
            "Hint: the base/default images may not exist yet — run "
            "./harvest.py (and confirm the docker-compose build step) first.",
            file=sys.stderr,
        )

    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
