#!/usr/bin/env python3
"""
till.py — Scaffold a new DockerSeed project directory.

Usage:
    ./till.py              # initialize the current working directory
    ./till.py <directory>  # initialize a path relative to the current directory

Writes the files needed to run sow.py, tend.py, and harvest.py.
Never overwrites existing files: if any planned file already exists,
the script reports them and exits without writing anything.
If the target directory does not exist, the user is asked whether to create it.
"""

import json
import sys
from pathlib import Path

SCRIPT_DIR: Path = Path(__file__).resolve().parent
ENV_SRC: Path = SCRIPT_DIR / ".env"

RED = "\033[31m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
BLUE = "\033[34m"
GREY = "\033[37m"
RESET = "\033[0m"

PLANNED_FILES: tuple[str, ...] = (
    "containers.json",
    ".env",
    ".gitignore",
    "secrets/README",
    "secrets/ssh/README",
)

PLANNED_DIRS: tuple[str, ...] = (
    "secrets",
    "secrets/ssh",
)

DEFAULT_CONTAINERS: list[dict[str, object]] = [
    {
        "name": "default",
        "enabled": True,
        "templates": [],
    }
]

GITIGNORE_CONTENT: str = """\
# Generated by DockerSeed
services/
docker-compose.yaml
common/
assets/
assets.json

# Local secrets
secrets/*
!secrets/ssh
!secrets/README
secrets/ssh/*
!secrets/ssh/README

__pycache__/
"""

SECRETS_README: str = """\
# Secrets

Place various secrets in this directory. It is excluded from the repository.
"""

SSH_SECRETS_README: str = """\
# SSH Keys

Create or copy the SSH keys required for authentication in the Git repository within this directory.
"""


def resolve_target(arg: str | None, cwd: Path) -> Path:
    if arg is None:
        return cwd.resolve()
    return (cwd / arg).resolve()


def existing_planned_paths(target: Path) -> list[str]:
    """Return relative paths that already exist and would be overwritten."""
    found: list[str] = []
    for rel in PLANNED_DIRS:
        path = target / rel
        if path.exists() and not path.is_dir():
            found.append(rel)
    for rel in PLANNED_FILES:
        path = target / rel
        if path.exists():
            found.append(rel)
    return found


def env_content(project: str, env_src: Path) -> str:
    if env_src.is_file():
        lines: list[str] = []
        replaced = False
        for line in env_src.read_text().splitlines(keepends=True):
            stripped = line.rstrip("\n")
            if stripped.startswith("PROJECT="):
                newline = "\n" if line.endswith("\n") else ""
                lines.append(f"PROJECT={project}{newline}")
                replaced = True
            else:
                lines.append(line)
        if not replaced:
            if lines and not lines[-1].endswith("\n"):
                lines[-1] = lines[-1] + "\n"
            lines.append(f"PROJECT={project}\n")
        return "".join(lines)

    return (
        "GIT_AUTHOR_NAME=\n"
        "GIT_AUTHOR_EMAIL=\n"
        "CONTAINER_USER=user\n"
        "CONTAINER_USER_ID=1337\n"
        f"PROJECT={project}\n"
        "SSH_KNOWN_HOSTS=github.com gitlab.com bitbucket.org ssh.dev.azure.com\n"
    )


def write_project(target: Path, env_src: Path) -> list[str]:
    """Create planned files. Caller must have verified none already exist."""
    written: list[str] = []
    (target / "secrets" / "ssh").mkdir(parents=True, exist_ok=True)

    files: dict[str, str] = {
        "containers.json": json.dumps(DEFAULT_CONTAINERS, indent=4) + "\n",
        ".env": env_content(target.name, env_src),
        ".gitignore": GITIGNORE_CONTENT,
        "secrets/README": SECRETS_README,
        "secrets/ssh/README": SSH_SECRETS_README,
    }
    for rel, content in files.items():
        path = target / rel
        path.write_text(content)
        written.append(rel)
    return written


def confirm_create(target: Path) -> bool:
    answer = input(
        f"Directory {target} does not exist. Create it? [y/N]: "
    ).strip().lower()
    return answer in ("y", "yes")


def print_next_steps(target: Path, cwd: Path) -> None:
    sow = SCRIPT_DIR / "sow.py"
    tend = SCRIPT_DIR / "tend.py"
    harvest = SCRIPT_DIR / "harvest.py"
    print(f"\n{BLUE}⚙{RESET} Next:")
    if target.resolve() != cwd.resolve():
        print(f"\t{GREY}◦{RESET} cd {target}")
    print(f"\t{GREY}◦{RESET} {sow}")
    print(f"\t{GREY}◦{RESET} {tend}   # if sow.py wrote assets.json")
    print(f"\t{GREY}◦{RESET} {harvest}")


def main() -> None:
    if len(sys.argv) > 2:
        print(f"Usage: {sys.argv[0]} [directory]", file=sys.stderr)
        sys.exit(1)

    cwd = Path.cwd()
    arg = sys.argv[1] if len(sys.argv) == 2 else None
    target = resolve_target(arg, cwd)

    if target.exists() and not target.is_dir():
        print(f"{RED}✗{RESET} {target} exists and is not a directory.")
        sys.exit(1)

    if not target.exists():
        if not confirm_create(target):
            print(f"{GREY}◦{RESET} Skipped. Directory was not created.")
            sys.exit(1)
        target.mkdir(parents=True)
        print(f"{GREEN}✓{RESET} Created {target}")

    conflicts = existing_planned_paths(target)
    if conflicts:
        print(f"{RED}✗{RESET} Refusing to overwrite existing files:")
        for rel in conflicts:
            print(f"\t{YELLOW}◦{RESET} {target / rel}")
        print(f"{GREY}◦{RESET} Nothing was written.")
        sys.exit(1)

    written = write_project(target, ENV_SRC)
    print(f"{GREEN}✓{RESET} Initialized DockerSeed project in {target}")
    for rel in written:
        print(f"\t{GREY}◦{RESET} {rel}")
    print_next_steps(target, cwd)


if __name__ == "__main__":
    main()
