services:
    cli:
        extends:
            file: ../common/base.yaml
            service: base # Use 'gpu' to enable GPU support
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
        build:
            context: .
            additional_contexts:
                localhost/base: service:base
volumes:
    root:
