FROM localhost/base

ARG USER
ARG PROJECT

# USER root
# RUN apt-get -y install <packages needed to run the project>
# USER ${USER}

# Directories for any additional volumes must be created here to ensure writing
# permissions from within the container.

WORKDIR /home/${USER}/${PROJECT}
