services:
    test_err:
        hostname: ${PROJECT}-test_err
        extends:
            file: ../common/docker-compose.yaml
            service: base
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
            - npm:/home/${CONTAINER_USER}/.npm
            - node:/home/${CONTAINER_USER}/.node
        build:
            context: .
            additional_contexts:
                localhost/base: service:base
        ports:
            - 10080:8080

volumes:
    root:
    npm:
    node:
