services:
    jupyter:
        hostname: ${PROJECT}-jupyter
        extends:
            file: ../common/docker-compose.yaml
            service: base
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
            - env:/home/${CONTAINER_USER}/env
            - cache:/home/${CONTAINER_USER}/.cache/pip
            - jupyter:/home/${CONTAINER_USER}/.jupyter
        build:
            context: .
            additional_contexts:
                localhost/base: service:base
        ports:
            - 8888:8888
        environment:
            PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
            PIP_INDEX_URL: ${PIP_INDEX_URL}

volumes:
    root:
    env:
    cache:
    jupyter:
