services:
    jupyter:
        extends:
            file: ../common/base.yaml
            service: base # Use 'gpu' to enable GPU support
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
            - env:/home/${CONTAINER_USER}/env
        build:
            context: .
            additional_contexts:
                localhost/base: service:python
        ports:
            - 8888:8888
volumes:
    root:
    env:
    # TODO: Add a volume for the JupyterLab extensions
