services:
    python:
        extends:
            file: ../common/docker-compose.yaml
            service: base
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
            - env:/home/${CONTAINER_USER}/env
        build:
            context: .
            additional_contexts:
                localhost/base: service:base
volumes:
    root:
    env:
