services:
    python:
        hostname: ${PROJECT}-python
        extends:
            file: ../common/docker-compose.yaml
            service: base
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
            - env:/home/${CONTAINER_USER}/env
            - cache:/home/${CONTAINER_USER}/.cache/pip
        build:
            context: .
            additional_contexts:
                localhost/base: service:base
        environment:
            PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
            PIP_INDEX_URL: ${PIP_INDEX_URL}
        networks:
            - python_net

volumes:
    root:
    env:
    cache:

networks:
    python_net:
        external: true
