services:
    gui:
        hostname: ${PROJECT}-gui
        extends:
            file: ../../common/docker-compose.yaml
            service: base
        init: true
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
        build:
            context: .
            additional_contexts:
                localhost/base: service:base
        ports:
            - 8900:5900

volumes:
    root:
