services:
    ollama:
        hostname: ${PROJECT}-ollama
        extends:
            file: ../common/docker-compose.yaml
            service: gpu
        volumes:
            - root:/home/${CONTAINER_USER}/${PROJECT}
            - ollama_storage:/home/${CONTAINER_USER}/.ollama
        build:
            context: .
            additional_contexts:
                localhost/base: service:base
        ports:
            - 11434:11434
        networks:
            - ollama_network

volumes:
    root:
    ollama_storage:

networks:
    ollama_network:
        external: true
