services:
    base:
        build:
            context: .
            additional_contexts:
                base: ../common
            args:
                USER: ${CONTAINER_USER}
                USER_ID: ${CONTAINER_USER_ID}
                PROJECT: ${PROJECT}
                GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL}
                GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME}

# TODO: The 'gpu' comfiguration was refactored from being a base service to
# an inline configuration. However, this means that it is much less flexibe,
# considering it might to be reconfigured for different host machines.
