services:
    base:
        cap_drop: ["all"]
        security_opt: ["no-new-privileges"]
        user: ${CONTAINER_USER_ID}:${CONTAINER_USER_ID}
        build:
            context: .
            additional_contexts:
                base: ../common
            args:
                USER: ${CONTAINER_USER}
                USER_ID: ${CONTAINER_USER_ID}
                PROJECT: ${PROJECT}
                GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL}
                GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME}

    gpu:
        extends:
            service: base
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
                          count: all
